title = "Miguel Lopez"
baseURL = "https://ktm888.github.io"
theme = "hugo-resume"
languageCode = "en-gb"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
cannonifyURLs = true
[params]
address = "London, UK"
email = "miguelgallego1@outlook.com"
favicon = "/favicon.ico"
firstName = "Miguel"
lastName = "Lopez"
phone = "+4478283885888"
profileImage = "img/profile_2.jpeg"
showEducation = true
showExperience = false
showOpenSource = false
showblog = true
showProjects = true
showPublications = false
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "G-MMFZT5WKK9"

[[params.handles]]
link = "https://www.linkedin.com/in/miguellopezg/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/KTM888/"
name = "GitHub"


[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"